---
title: Gemma Holloway Fitness
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/recipes/:path"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: recipes
  values:
    layout: recipe
    permalink: "/recipes/:title/"
    serves: 2
    preparation_time: 15mins
    ingredients:
    steps:
    -
- scope:
    path: ''
    type: pages
  values:
    layout: page
contact:
  email: gemma@vixenfitness.co.uk
  social:
    twitter: VixenFitnessUK
    facebook: VixenFitnessUK
    instagram: VixenFitnessUK
    snapchat: gemgemwings
keep_files:
- css
- js
- img
exclude:
- gulpfile.coffee
- package.json
- yarn.lock
- node_modules
permalink: pretty
