---
title: Wings Fitness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "/blog"
    type: posts
  values:
    layout: article
    permalink: "/blog/:title/"
- scope:
    path: "/recipes"
    type: recipes
  values:
    layout: recipe
    permalink: "/recipes/:title/"
    ingredients:
      Ingredient: amount
    steps:
    - 
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
