---
title: Gemma Holloway Fitness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/recipes/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: recipes
  values:
    layout: recipe
    permalink: "/recipes/:title/"
    serves: 2
    preparation_time: 15mins
    ingredients: 
    steps:
    - 
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
