---
title: Wings Fitness
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
  recipes:
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "_articles"
    type: articles
  values:
    layout: article
    permalink: "/blog/:title/"
- scope:
    path: "_recipes"
    type: recipes
  values:
    layout: recipe
    permalink: "/recipes/:title/"
    ingredients:
      Ingredient: amount
    steps:
    - 
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
